# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/testapp-252513/bitbucket.org/bikeshr/testrepo:$SHORT_SHA', '.']

steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: [app, deploy]
  dir: 'client'

- name: "gcr.io/cloud-builders/gcloud"
  args: [app, deploy]
  dir: 'server'
